title: Jesskidding's awesome Knowledge Base of Information Technology Cybersecurity and Computer Science concepts.
author: Jesskidding
description: Some things I found useful for IT programming and hacking.
theme: minima
